image: docker:latest

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - docker-compose version
  - echo "y" | docker network prune
  - docker network create my_network

build:
  stage: build
  script:
    - docker compose -f docker-compose.prod.yml build
  only:
    - main

deploy:
  stage: deploy
  script:
    - docker-compose down || true
    - docker-compose -f docker-compose.prod.yml up -d
    - echo "y" | docker system prune
  only:
    - main
  when: manual
